#+TITLE: Nadeŭka's dotfiles
#+AUTHOR: Nadeŭka
#+DATE: [2025-2-8 Sat]

[[https://builtwithnix.org/][https://builtwithnix.org/badge.svg]]
[[https://nixos.org][https://img.shields.io/badge/NixOS-unstable-5176c2?style=for-the-badge&logo=nixos&logoColor=7db9e3.svg]]
[[file:LICENSE][https://img.shields.io/github/license/nadevko/dotfiles?style=for-the-badge&color=822422&logo=spdx.svg]]
# [[https://nadevko.cachix.org][https://img.shields.io/badge/cachix-nadevko-blue.svg?style=for-the-badge]]

My personal [[https://github.com/nix-community/NUR][NUR]]-compatible dotfiles
repository.

Inb4: Flakes? Let's wait until they become stable.

** Repository structure

The repository is organized into the following directories:

# - [[#Packages][pkgs]]/ :: Nix packages.
- [[#NixOS][nixos]]/ :: Houses the NixOS system configurations.
  - [[#iso][iso]]/ :: Setup for removable flash drives.
# - [[#Home-manager][hm]]/ :: Contains the configurations for home-manager that
#   I use.
# - [[#Nix-on-droid][droid]]/ :: Stores nix-on-droid configurations, a nix-enabled
#   Termux fork.
- [[#Modules][modules]]/ :: Directories with definitions of option modules.
  - [[#nixpkgs][nixpkgs]] :: Overlays management.
  - [[#secrix][secrix]] :: Setup secrix tool to manage secrets.
- [[#Overlays][overlays]]/ :: Nix overlays.
  - [[#maintainer][maintainer]] :: This repository.
  - [[#nur][nur]] :: Packages from nix user repository.
- [[#Library][lib]]/ :: Nix helper functions.
  - [[#trivial][trivial]] :: Miscellaneous functions
  - [[#attrsets][attrsets]] :: Attribute set functions

Note: Modules for both home-manager and NixOS are placed together within this
unified structure using the ~_class~ option.

** NixOS

*** iso

Thats a minimal iso image extended by all hardware support and tools to install
other distributions and for repairement.

For now, can be installed:

~NixOS~ :: Via ~nixos-install~, ~disko-install~ or ~nixos-anywhere~.

~Arch-based distros~ :: Via ~pacstrap~.

~Debian-based distros~ :: Via ~debootstrap~.

~Rpm family distros~ :: Via ~dnf~ and ~kickstart~.

** Modules

*** nixpkgs

nixpkgs.compat :: Whether to enable overlays compatibility for tools.

*** secrix

This module imports secrix and installs ~secrix~ tool to manage it, if any
secret exist.

** Overlays

*** maintainer

Overlay with all [[#Packages][packages]] and lib extended by
[[#Library][library]] functions.

*** nur

Just a [[https://github.com/nix-community/NUR][NUR]] overlay.

** Library

*** trivial

getFlake = Path -> { defaultNix, shellNix, outputs } :: Function to use flakes
  with stable nix.

*** attrsets

attrsets.loadDir = (Path -> Any) -> Path -> AttrSet :: Read directory and make
  map of nix files without nix extension and directories to results of
  processing file paths in it by passed function.
