#+TITLE: Nadeŭka's dotfiles
#+AUTHOR: Nadeŭka
#+DATE: [2025-2-5 Wed]

[[https://builtwithnix.org/][https://builtwithnix.org/badge.svg]]
[[https://nixos.org][https://img.shields.io/badge/NixOS-unstable-5176c2?style=for-the-badge&logo=nixos&logoColor=7db9e3.svg]]
[[file:LICENSE][https://img.shields.io/github/license/nadevko/dotfiles?style=for-the-badge&color=822422&logo=spdx.svg]]
# [[https://nadevko.cachix.org][https://img.shields.io/badge/cachix-nadevko-blue.svg?style=for-the-badge]]

My personal [[https://github.com/nix-community/NUR][NUR]]-compatible dotfiles
repository.

Inb4: Flakes? Let's wait until they become stable.

** Repository structure

The repository is organized into the following directories:

- hm/ :: Contains the configurations for home-manager that I use.
- [[*NixOS][nixos]]/ :: Houses the NixOS system configurations.
  - [[*kinstra]]/ :: Minimal ISO setup for flash drives with repair and install
	  tools.
- droid/ :: Stores nix-on-droid configurations, a nix-enabled Termux fork.
- overlays/ :: Nix overlays.
- [[*Libraries][lib]]/ :: Nix helper functions.
- pkgs/ :: Nix packages.
- [[*Modules][modules]]/ :: Directories with definitions of option modules.
  - [[*Nixpkgs][nixpkgs]]/ :: Provides options to set up channels and overlays.

Note: Modules for both home-manager and NixOS are placed together within this
unified structure using the ~_class~ option.

** NixOS

*** kinstra

Minimal ISO setup for flash drives with repair and install tools.

** Libraries

** Modules

*** Nixpkgs

~nixpkgs.reposPath~ ::
	The value of this option is a attrset where name used as id of repository in
	options; path is file with function that accepts current pkgs as argument
	(like in nixpkgs) and returns their overrides; description is pretty name of
	the repository.

  {
  	name = {
  		path = ./repo.nix;
  		description = "beautiful name";
  	};
  }

~nixpkgs.repos~ ::
  Setting repository id to true adds its packages to packageOverrides and
  provides them as module arguments. In the first case all packages are
  prefixed with repository id.

~nixpkgs.repos.nadevko~ ::
	Whether to enable nadevko's personal packages. This option separately loads
	this repository, because of several reasons:

  - As of [2025-2-5 Wed], the repository is not added to the NUR.
  - To use during development on localhost.

~nixpkgs.repos.nur~ ::
	Whether to enable nix user repository.
