= Some comfy dots

== NixOS

=== Configurations

klinicyst:: Main laptop configuration
flash:: Installation ISO configuration for flash drives
cyrykiec:: Home server configuration (now not in use)

=== Modules

agenix:: Module to autosetup age in nixos modules using extra secrets.nix fields

== home-manager

=== Configurations

nadevko:: My home-manager configuration

=== Modules

gnome:: Helper to bundle extension dconf settings with extension itself
firefox-gnome-theme:: Module to install and configure `firefox-gnome-theme`

== Packages

firefox-gnome-theme:: A GNOME theme for Firefox
firefoxAddons-dollchan-extension:: firefox addon dollchan-extension
firefoxAddons-shikiplayer:: firefox addon shikiplayer
oracle-datamodeler:: Data modeling and database design tool from Oracle
buildFirefoxXpiAddon:: rycee's buildFirefoxXpiAddon but declared as a package to be overridden
firefoxPipTitles:: Helper to fetch and format as json Firefox Picture-in-Picture titles for all or defined locales
fuzzmenu:: A simple fuzzy menu applications launcher script
gh-milestone:: A command line tool for managing GitHub milestones
gost-fonts:: GOST fonts for NixOS
hyprlandWindowRules:: Hyprland firefoxPipTitles wrapper
