{
  inputs,
  lib,
  writeText,
  stdenvNoCC,
  grex,
  jq,
  rules ? [
    {
      rules = [
        "float"
        "pin"
        "move 72% 72%"
        "keepaspectratio"
      ];
      class = "^com.(ayu|tele)gram.desktop$";
      title = "^(AyuG|Teleg)ramDesktop$";
    }
  ],
  defaultRules ? [
    "float"
    "pin"
    "move 72% 72%"
    "size 25%"
    "keepaspectratio"
  ],
  firefoxPipTitles ? null,
  firefoxClass ? null,
  firefoxRules ? defaultRules,
}:
let
  inherit (builtins) all concatStringsSep;
  inherit (lib.strings) optionalString escapeShellArgs;
  inherit (lib.lists) optional;
  inherit (lib) licenses platforms;

  allRules =
    (optional (firefoxPipTitles != null) {
      class = firefoxClass;
      title = "@FF_PIP@";
      rules = firefoxRules;
    })
    ++ rules;

  rulesArr = escapeShellArgs (
    map (
      r: concatStringsSep ";" (if r ? rules && r.rules != null then r.rules else defaultRules)
    ) allRules
  );
  ruleFieldToShellArr = name: escapeShellArgs (map (r: r.${name} or "") allRules);
in
assert all (r: (r.title or null) != null || (r.class or null) != null) rules;
stdenvNoCC.mkDerivation {
  pname = "hyprland-window-rules";
  version = "0.1";

  dontUnpack = true;

  src = writeText "hyprland.conf" ''
    # This file is autogenerated
    ${optionalString (firefoxPipTitles != null) ''
      # +firefoxPipTitles v${firefoxPipTitles.version or "unknown"}
    ''}
  '';

  inherit firefoxPipTitles;

  nativeBuildInputs = [
    grex
    jq
  ];

  buildPhase = ''
    cat "$src" > hyprland.conf

    c_list=( ${ruleFieldToShellArr "class"} )
    t_list=( ${ruleFieldToShellArr "title"} )
    r_list=( ${rulesArr} )

    if [[ -f "$firefoxPipTitles" ]]; then
      FF_REGEXP=$(jq -r 'values[]' "$firefoxPipTitles" | sort -u | xargs -r grex | head -c -1)
    fi

    {
      for i in "''${!c_list[@]}"; do
        class="''${c_list[$i]}"
        title="''${t_list[$i]}"
        rules="''${r_list[$i]}"
        [[ "$title" == "@FF_PIP@" ]] && title="$FF_REGEXP"
        entry="windowrulev2 = $rules"
        [[ -n "$class" ]] && entry+=", class:$class"
        [[ -n "$title" ]] && entry+=", title:$title"
        echo "$entry"
      done
    } >> hyprland.conf
  '';

  installPhase = ''
    runHook preInstall
    cp hyprland.conf "$out"
    runHook postInstall
  '';

  meta = {
    description = "Hyprland window rules configuration file";
    homepage = "https://github.com/nadevko/dotfiles";
    license = licenses.eupl12;
    maintainers = with inputs.self.lib.maintainers; [ nadevko ];
    platforms = platforms.linux;
  };
}
