{ config, lib, pkgs, ... }:
with lib;
let
  cfg = config.programs.nano;

  colors = with types;
    either (strMatching "^#[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]$")
    (enum (import ./colornames.nix));
  paths = import ./paths.nix;

  mkFlagOption = name: description:
    mkOption {
      type = with types; nullOr bool;
      default = null;
      example = true;
      description = description;
    };
  mkTypeOption = type: example: name: description:
    mkOption {
      type = types.nullOr type;
      default = null;
      example = example;
      description = description;
    };
  mkColorOption = name: description:
    mkOption {
      type = types.submodule {
        options = {
          bold = mkOption {
            type = types.bool;
            default = false;
            apply = value: optionalString value "bold,";
          };
          italic = mkOption {
            type = types.bool;
            default = false;
            apply = value: optionalString value "italic,";
          };
          fgcolor = mkOption {
            type = types.nullOr colors;
            default = null;
            apply = value:
              optionalString (!isNull value) (if isList value then
                "#${concatStrings (map (value: toString value) value)}"
              else
                value);
          };
          bgcolor = mkOption {
            type = types.nullOr colors;
            default = null;
            apply = value: optionalString (!isNull value) value;
          };
        };
      };
      example = {
        bold = true;
        fgcolor = "pink";
        bgcolor = "#4FF";
      };
      default = { };
      description = description;
      apply = value:
        optionalString (value.fgcolor != "" || value.bgcolor != "") ''
          set ${name} ${value.bold}${value.italic}${value.fgcolor}${
            optionalString (value.fgcolor != "" && value.bgcolor != "") ","
          }${value.bgcolor}
        '';
    };
in {
  options.programs.nano = {
    enable = mkEnableOption "nano";
    package = mkPackageOption pkgs "nano" { };
    config = mkOption {
      type = types.submodule {
        options = (mapAttrs mkFlagOption (import ./flags.nix))
          // (mapAttrs (mkTypeOption types.str "<[({})]>") (import ./chars.nix))
          // (mapAttrs (mkTypeOption types.int 80) (import ./nums.nix))
          // (mapAttrs
            (mkTypeOption types.path (xdg.cacheHome + "/nano/nanorc")) paths)
          // (mapAttrs mkColorOption (import ./colors.nix));
      };
      example = ''
        atblanks = true;
      '';
      description = "Set of nano's options";
    };
    bindings = mkOption {
      type = with types;
        listOf (submodule {
          options = {
            key = mkOption {
              type = strMatching
                "^(\\^([A-Z@\\\\\\^_]|]|Space)|M-([ -Z\\\\-~]|Space)|Sh-M-[A-Z]|F(1?[1-9]|10|2[0-4])|Ins|Del)$";
            };
            function = mkOption {
              type =
                either str (enum ((import ./functions.nix) ++ [ "unbind" ]));
            };
            menu = mkOption { type = enum (import ./menus.nix); };
          };
        });
      example = {
        key = "^Z";
        function = "unbind";
        menu = "help";
      };
      description =
        "Set key to do function in the menu. 'unbind' to do nothing";
    };
    includes = mkOption {
      type = with types; listOf (package);
      default = [ ];
      example = [ pkgs.nano ];
      description = "List of packages with nanorcs in share/nano dir";
    };
    extra = mkOption {
      type = with types; listOf (either path lines);
      default = [ ];
      description = "List of parts of nanorc";
      apply = value:
        concatStrings (if isPath value then readFile value else value);
    };
  };
  config = mkIf cfg.enable {
    home.packages = [ cfg.package ];
    programs.nano.extra = [''
      # configuration generated by NIX
      # programs.nano.config
    ''] ++ (attrValues (mapAttrs (name: value:
      optionalString (value != null && value != "") ''
        ${optionalString (value == false) "un"}set ${name}${
          optionalString (!isBool value) " ${toString value}"
        }
      '') cfg.config)) ++ [''
        # programs.nano.bindings
      ''] ++ (map (value: ''
        ${if value.function == "unbind" then
          "unbind ${value.key} ${value.menu}"
        else
          "bind ${value.key} ${value.function} ${value.menu}"}
      '') cfg.bindings) ++ [''
        # programs.nano.include
      ''] ++ (map (value:
        ''
          include "${value}/share/nano/*.nanorc"
        '' + (optionalString (value == cfg.package) ''
          include "${value}/share/nano/extra/*.nanorc"
        '')) cfg.includes) ++ [''
          # programs.nano.extra
        ''];
    xdg.configFile."nano/nanorc" = {
      text = cfg.extra;
      onChange = let
        options = attrValues (filterAttrs (name: value:
          any (pathOption: name == pathOption && !isNull value)
          (attrNames paths)) cfg.config);
      in optionalString (paths != [ ]) ''
        mkdir --verbose --parent '${concatStringsSep "' '" options}'
      '';
    };
  };
}
