utf8-strings
keyid-format 0xlong

expert
no-greeting
with-fingerprint

no-emit-version
no-comments
require-secmem

personal-digest-preferences SHA512 SHA384 SHA256 SHA224
default-preference-list SHA512 SHA384 SHA256 SHA224 AES256 AES192 AES CAST5 BZIP2 ZLIB ZIP Uncompressed
cert-digest-algo SHA512
s2k-cipher-algo AES256
s2k-digest-algo SHA512

keyserver-options no-honor-keyserver-url

sig-notation issuer-fpr@notations.openpgp.fifthhorseman.net=%g
