{ config, lib, pkgs, ... }:
with lib;
let cfg = config.programs.vim;
in {
  disabledModules = [ <home-manager/modules/programs/vim.nix> ];
  options.programs.vim = {
    enable = mkEnableOption "vim";
    package = mkPackageOption pkgs "vim" {
      default = "vim-full";
      example = "vim_configurable";
    };
    plugins = mkOption {
      type = with types; listOf (either (path) (package));
      default = [ ];
      example = [ pkgs.vimPlugins.vim-nix ];
      description = "Lists of plugins to install";
    };
    extraConfig = mkOption {
      type = types.lines;
      default = "";
      example = ''
        set nocompatible
        set nobackup
      '';
      description = "Extra contents for vimrc";
    };
    extraGuiConfig = mkOption {
      type = types.lines;
      default = "";
      example = ''
        set nocompatible
        set nobackup
      '';
      description = "Extra contents for gvimrc";
    };
  };
  config = mkIf cfg.enable {
    home.packages = [
      (cfg.package.customize {
        vimrcConfig = {
          beforePlugins = ''
            " configuration generated by NIX
          '';
          customRC = ''
            ${cfg.extraConfig}
          '';
          packages.home-manager = { start = cfg.plugins; };
        };
        gvimrcFile = cfg.extraGuiConfig;
      })
    ];
  };
}
